apiVersion: v1
kind: Pod
metadata:
  name: pincong-mariadb
  namespace: pincong
  labels:
    app: pincong
    service: pincong-mariadb
spec:
  containers:
    - name: pincong-mariadb
      image: pincong-mariadb
      imagePullPolicy: Never
      ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_DATABASE
          value: "db"
        - name: MYSQL_USER
          value: "user1"
        - name: MYSQL_PASSWORD
          value: "123456"
