apiVersion: v1
kind: Service
metadata:
  name: pincong-mariadb
  namespace: pincong
  labels:
    app: pincong
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
    service: pincong-mariadb
